version: '3.4'

services:
  thaioilpalmspectro:
    image: thaioilpalmspectro
    build:
      context: .
      dockerfile: ./Dockerfile
    command: ["sh", "-c", "pip install debugpy -t /tmp && python /tmp/debugpy --wait-for-client --listen 0.0.0.0:5678 run_all_process_V1_0.py "]
    ports:
      - 5678:5678
